### ISSUE TITLE
[bug] CI might not be correctly uploading to codecov

### ISSUE THREAD

**Issue by ethanholz** [omsf-eco-infra/gha-runner#4]
Upon the first run of this action there seems to be an issue that arose wherein the coverage is not being uploaded correctly to `codecov`.  This can be seen in each run in the matrix. I have run the build again to validate that this issue persists.

Examples:
- https://github.com/omsf-eco-infra/gha-runner/actions/runs/9022758246/job/24793030788#step:8:60
- https://github.com/omsf-eco-infra/gha-runner/actions/runs/9022758246/job/24793031057#step:8:60
- https://github.com/omsf-eco-infra/gha-runner/actions/runs/9022758246/job/24793031363#step:8:60

Two things to note from this:
1. We will need to add a way to add a badge or some other integration to validate that the results are being uploaded.
2. There may be an issue in how we are authenticating and the token may need to be replaced.

**Comment by ethanholz** [comment]
@dwhswenson tagging for visibility.

**Comment by dwhswenson** [comment]
Based on trouble I had getting CodeCov to show me the omsf-eco-infra version of the repo today, my guess is that I somehow managed to create a token for my fork, not this version of the repo.

Looks like it works now: https://app.codecov.io/gh/omsf-eco-infra/gha-runner

Closing, feel free to reopen if I've misunderstood!
